### ISSUE TITLE
Setup error (Windows)

### ISSUE THREAD

**Issue by MaximeFRA** [minotaur-ergo/minotaur-wallet#7]
Hello, 

I tried to install it but I got this error : 

Unhandled Promise Rejection
TypeError: Cannot read properties of undefined (reading 'CapacitorSQLite')
    at new UtilsFile (C:/Users/Maxime/AppData/Local/Programs/minotaur-wallet/resources/app.asar/node_modules/@capacitor-community/sqlite/electron/dist/plugin.js:2198:54)
    at new CapacitorSQLite (C:/Users/Maxime/AppData/Local/Programs/minotaur-wallet/resources/app.asar/node_modules/@capacitor-community/sqlite/electron/dist/plugin.js:3413:23)
    at Object.R (C:/Users/Maxime/AppData/Local/Programs/minotaur-wallet/resources/app.asar/node_modules/@capacitor-community/electron/dist/core/index.js:1:2349)
    at ElectronCapacitorApp.init (C:/Users/Maxime/AppData/Local/Programs/minotaur-wallet/resources/app.asar/build/src/setup.js:178:20)
    at C:/Users/Maxime/AppData/Local/Programs/minotaur-wallet/resources/app.asar/build/src/index.js:41:26

Hope its helps

Maxime

**Comment by vorujack** [comment]
This error cause from exernal package. 

please use 1.0.3 version and wait to fix this bug

**Comment by MaximeFRA** [comment]
I confirm, it works fine in 1.0.3, Thanks for the quick reply vorujack !

**Comment by MaximeFRA** [comment]
This error cause from exernal package.

please use 1.0.3 version and wait to fix this bug
