### ISSUE TITLE
Error after fresh windows install.

### ISSUE THREAD

**Issue by Aquaritek** [minotaur-ergo/minotaur-wallet#9]
Freshly installed latest version on windows 11 attempted to open the application and this was the error presented to me:

Unhandled Promise Rejection
TypeError: Cannot read properties of undefined (reading 'CapacitorSQLite')
    at new UtilsFile (C:/Users/hdust/AppData/Local/Programs/minotaur-wallet/resources/app.asar/node_modules/@capacitor-community/sqlite/electron/dist/plugin.js:2198:54)
    at new CapacitorSQLite (C:/Users/hdust/AppData/Local/Programs/minotaur-wallet/resources/app.asar/node_modules/@capacitor-community/sqlite/electron/dist/plugin.js:3413:23)
    at Object.R (C:/Users/hdust/AppData/Local/Programs/minotaur-wallet/resources/app.asar/node_modules/@capacitor-community/electron/dist/core/index.js:1:2349)
    at ElectronCapacitorApp.init (C:/Users/hdust/AppData/Local/Programs/minotaur-wallet/resources/app.asar/build/src/setup.js:178:20)
    at C:/Users/hdust/AppData/Local/Programs/minotaur-wallet/resources/app.asar/build/src/index.js:41:26

**Comment by gorgarp** [comment]
Same. Windows 11 as well.

Unhandled Promise Rejection
TypeError: Cannot read properties of undefined (reading 'CapacitorSQLite')
    at new UtilsFile (C:/Program Files/minotaur-wallet/resources/app.asar/node_modules/@capacitor-community/sqlite/electron/dist/plugin.js:2198:54)
    at new CapacitorSQLite (C:/Program Files/minotaur-wallet/resources/app.asar/node_modules/@capacitor-community/sqlite/electron/dist/plugin.js:3413:23)
    at Object.R (C:/Program Files/minotaur-wallet/resources/app.asar/node_modules/@capacitor-community/electron/dist/core/index.js:1:2349)
    at ElectronCapacitorApp.init (C:/Program Files/minotaur-wallet/resources/app.asar/build/src/setup.js:178:20)
    at C:/Program Files/minotaur-wallet/resources/app.asar/build/src/index.js:41:26

**Comment by gorgarp** [comment]
tried rolling back to 1.0.3, still get Unhandled Error
Error: SQLITE_CANTOPEN: unable to open database file

**Comment by vorujack** [comment]
Version 1.0.4 has an library error. It will be solved in next version.

we will check it on windows 11.

**Comment by vorujack** [comment]
New version released. this version tested on windows 10.

please verify it on your system.
